# Generated by Django 4.2.2 on 2025-04-24 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('stock_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUNES', 'LUNES'), ('MARTES', 'MARTES'), ('MIERCOLES', 'MIERCOLES'), ('JUEVES', 'JUEVES'), ('VIERNES', 'VIERNES'), ('SABADO', 'SABADO')], default='LUNES', max_length=10)),
                ('id_sheet', models.CharField(choices=[('ID1', 'ID1'), ('ID2', 'ID2'), ('ID3', 'ID3'), ('ID4', 'ID4'), ('ID5', 'ID5'), ('ID6', 'ID6')], default='ID1', max_length=4)),
                ('id_usuario', models.IntegerField()),
                ('v_vendedor', models.BooleanField(default=False)),
                ('d_despachador', models.BooleanField(default=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('descuentos', models.IntegerField(default=0)),
                ('adicional', models.IntegerField(default=0)),
                ('devoluciones', models.IntegerField(default=0)),
                ('vencidas', models.IntegerField(default=0)),
                ('valor', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('neto', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
    ]
