# Generated by Django 5.1.7 on 2025-04-05 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('stock_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('v_vendedor', models.BooleanField(default=False)),
                ('d_despachador', models.BooleanField(default=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('descuentos', models.IntegerField(default=0)),
                ('adicional', models.IntegerField(default=0)),
                ('devoluciones', models.IntegerField(default=0)),
                ('vencidas', models.IntegerField(default=0)),
                ('valor', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('neto', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
    ]
