# Generated by Django 4.2.2 on 2025-06-17 06:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_total', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(default='GENERICA', max_length=100)),
                ('impuesto', models.CharField(default='IVA(0%)', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='api.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUNES', 'LUNES'), ('MARTES', 'MARTES'), ('MIERCOLES', 'MIERCOLES'), ('JUEVES', 'JUEVES'), ('VIERNES', 'VIERNES'), ('SABADO', 'SABADO')], default='LUNES', max_length=10)),
                ('id_sheet', models.CharField(choices=[('ID1', 'ID1'), ('ID2', 'ID2'), ('ID3', 'ID3'), ('ID4', 'ID4'), ('ID5', 'ID5'), ('ID6', 'ID6')], default='ID1', max_length=4)),
                ('id_usuario', models.IntegerField()),
                ('v_vendedor', models.BooleanField(default=False)),
                ('d_despachador', models.BooleanField(default=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('descuentos', models.IntegerField(default=0)),
                ('adicional', models.IntegerField(default=0)),
                ('devoluciones', models.IntegerField(default=0)),
                ('vencidas', models.IntegerField(default=0)),
                ('valor', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('neto', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.CharField(max_length=100)),
                ('nota', models.TextField(blank=True, null=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='api.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='api.producto')),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='api.producto'),
        ),
    ]
