# Generated by Django 4.2.2 on 2025-06-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='codigo',
            new_name='lote',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='lote',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='usuario',
            field=models.CharField(default='Sistema', max_length=100),
        ),
    ]
