# Generated by Django 4.2.2 on 2025-06-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_update_lote_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lote',
            name='fecha_produccion',
            field=models.DateField(default='2025-06-17'),
        ),
    ]
