# Generated by Django 4.2.2 on 2025-06-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_cantidad_fecha_produccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='producto',
        ),
    ]
