# Generated by Django 4.2.2 on 2025-06-21 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_simplify_lote_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField()),
                ('producto_nombre', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha_produccion', models.DateField(default='2025-06-17')),
                ('usuario', models.CharField(default='Sistema', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
