# Generated by Django 4.2.2 on 2025-06-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_create_registro_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroinventario',
            name='entradas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroinventario',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroinventario',
            name='salidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroinventario',
            name='tipo_movimiento',
            field=models.CharField(default='ENTRADA', max_length=20),
        ),
    ]
