# Generated by Django 4.2.2 on 2025-07-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_venta_detalleventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
