# Generated by Django 4.2.2 on 2025-07-07 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_venta_numero_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regimen', models.CharField(choices=[('SIMPLIFICADO', 'Régimen Simplificado'), ('COMUN', 'Régimen Común')], default='SIMPLIFICADO', max_length=20)),
                ('tipo_persona', models.CharField(choices=[('NATURAL', 'Natural'), ('JURIDICA', 'Jurídica')], default='NATURAL', max_length=20)),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de extranjería'), ('PASAPORTE', 'Pasaporte')], default='CC', max_length=20)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_1', models.CharField(blank=True, max_length=20, null=True)),
                ('movil', models.CharField(blank=True, max_length=20, null=True)),
                ('email_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(default='Colombia', max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('zona_barrio', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_contacto', models.CharField(default='CLIENTE', max_length=50)),
                ('sucursal', models.CharField(default='Todas', max_length=100)),
                ('medio_pago_defecto', models.CharField(blank=True, max_length=50, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('permite_venta_credito', models.BooleanField(default=False)),
                ('cupo_endeudamiento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_vencimiento_cartera', models.IntegerField(default=30)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
