# Generated by Django 4.2.2 on 2025-07-31 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor'), ('EMPLEADO', 'Empleado')], default='CLIENTE', max_length=20)),
                ('empleado', models.CharField(blank=True, max_length=100, null=True)),
                ('sucursal', models.CharField(default='Principal', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilidad_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='api.listaprecio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='api.producto')),
            ],
            options={
                'unique_together': {('producto', 'lista_precio')},
            },
        ),
    ]
