# Generated by Django 4.2.2 on 2025-08-23 16:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_listaprecio_precioproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargueOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('usuario', models.CharField(default='Sistema', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('id_vendedor', models.CharField(choices=[('ID1', 'ID1'), ('ID2', 'ID2'), ('ID3', 'ID3'), ('ID4', 'ID4'), ('ID5', 'ID5'), ('ID6', 'ID6')], max_length=3, unique=True)),
                ('ruta', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ResumenTotales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_caja', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_despacho', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pedidos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_dctos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cargue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumen', to='api.cargueoperativo')),
            ],
        ),
        migrations.CreateModel(
            name='ResumenPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(blank=True, max_length=255, null=True)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nequi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daviplata', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cargue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.cargueoperativo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCargue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor_check', models.BooleanField(default=False)),
                ('despachador_check', models.BooleanField(default=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('dctos', models.IntegerField(default=0)),
                ('adicional', models.IntegerField(default=0)),
                ('devoluciones', models.IntegerField(default=0)),
                ('vencidas', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cargue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.cargueoperativo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.AddField(
            model_name='cargueoperativo',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargues', to='api.vendedor'),
        ),
        migrations.AlterUniqueTogether(
            name='cargueoperativo',
            unique_together={('dia', 'vendedor', 'fecha')},
        ),
    ]
