# Generated by Django 4.2.2 on 2025-09-12 12:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_cargueoperativo_vendedor_resumentotales_resumenpagos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteVencido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=100)),
                ('motivo', models.CharField(choices=[('HONGO', 'Hongo'), ('FVTO', 'FVTO'), ('SELLADO', 'Sellado')], max_length=20)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.CharField(default='Sistema', max_length=100)),
                ('detalle_cargue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_vencidos', to='api.detallecargue')),
            ],
            options={
                'verbose_name': 'Lote Vencido',
                'verbose_name_plural': 'Lotes Vencidos',
            },
        ),
    ]
