# Generated by Django 4.2.2 on 2025-09-13 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_lotevencido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCumplimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=10)),
                ('id_sheet', models.CharField(choices=[('ID1', 'ID1'), ('ID2', 'ID2'), ('ID3', 'ID3'), ('ID4', 'ID4'), ('ID5', 'ID5'), ('ID6', 'ID6')], max_length=3)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('licencia_transporte', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('soat', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('uniforme', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('no_locion', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('no_accesorios', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('capacitacion_carnet', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('higiene', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('estibas', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('desinfeccion', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('usuario', models.CharField(default='Sistema', max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Control de Cumplimiento',
                'verbose_name_plural': 'Controles de Cumplimiento',
                'unique_together': {('dia', 'id_sheet', 'fecha')},
            },
        ),
    ]
