# Generated by Django 4.2.2 on 2025-09-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_cantidadsugerida'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='responsable',
            field=models.CharField(blank=True, default='RESPONSABLE', max_length=100),
        ),
    ]
