# Generated by Django 4.2.2 on 2025-09-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_responsable_to_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargueoperativo',
            name='estado',
            field=models.CharField(choices=[('ALISTAMIENTO', 'Alistamiento'), ('DESPACHO', 'Despacho'), ('FINALIZAR', 'Finalizar'), ('COMPLETADO', 'Completado')], default='COMPLETADO', max_length=20),
        ),
    ]
