# Generated by Django 4.2.2 on 2025-09-23 05:29

from django.db import migrations

def set_default_estado(apps, schema_editor):
    """Establecer valor por defecto para el campo estado"""
    db_alias = schema_editor.connection.alias
    
    # Ejecutar SQL para establecer valor por defecto
    schema_editor.execute(
        "ALTER TABLE api_cargueoperativo ALTER COLUMN estado SET DEFAULT 'COMPLETADO';"
    )

def reverse_default_estado(apps, schema_editor):
    """Revertir valor por defecto para el campo estado"""
    db_alias = schema_editor.connection.alias
    
    # Ejecutar SQL para quitar valor por defecto
    schema_editor.execute(
        "ALTER TABLE api_cargueoperativo ALTER COLUMN estado DROP DEFAULT;"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_cargueoperativo_estado'),
    ]

    operations = [
        migrations.RunPython(set_default_estado, reverse_default_estado),
    ]
