# Generated by Django 4.2.2 on 2025-09-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_cargueid1_cargueid2_cargueid3_cargueid4_cargueid5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargueid1',
            name='responsable',
            field=models.CharField(blank=True, default='RESPONSABLE', max_length=100),
        ),
        migrations.AddField(
            model_name='cargueid2',
            name='responsable',
            field=models.CharField(blank=True, default='RESPONSABLE', max_length=100),
        ),
        migrations.AddField(
            model_name='cargueid3',
            name='responsable',
            field=models.CharField(blank=True, default='RESPONSABLE', max_length=100),
        ),
        migrations.AddField(
            model_name='cargueid4',
            name='responsable',
            field=models.CharField(blank=True, default='RESPONSABLE', max_length=100),
        ),
        migrations.AddField(
            model_name='cargueid5',
            name='responsable',
            field=models.CharField(blank=True, default='RESPONSABLE', max_length=100),
        ),
        migrations.AddField(
            model_name='cargueid6',
            name='responsable',
            field=models.CharField(blank=True, default='RESPONSABLE', max_length=100),
        ),
    ]
