# Generated by Django 4.2.2 on 2025-10-01 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_fix_fecha_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduccionSolicitada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=10)),
                ('fecha', models.DateField()),
                ('producto_nombre', models.CharField(max_length=255)),
                ('cantidad_solicitada', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('dia', 'fecha', 'producto_nombre')},
            },
        ),
    ]
