# Generated by Django 4.2.2 on 2025-10-08 01:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_produccionsolicitada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('CAJERO', 'Cajero'), ('SUPERVISOR', 'Supervisor'), ('ADMINISTRADOR', 'Administrador')], default='CAJERO', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('puede_hacer_descuentos', models.BooleanField(default=False)),
                ('limite_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('puede_anular_ventas', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cajero',
                'verbose_name_plural': 'Cajeros',
                'ordering': ['sucursal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('base_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arqueo_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_otros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('numero_transacciones', models.IntegerField(default=0)),
                ('notas_apertura', models.TextField(blank=True, null=True)),
                ('notas_cierre', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='api.cajero')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='api.sucursal')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='VentaCajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(default='POS-001', max_length=50)),
                ('numero_transaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_realizadas', to='api.cajero')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_sucursal', to='api.sucursal')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='api.turno')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_cajero', to='api.venta')),
            ],
            options={
                'verbose_name': 'Venta Cajero',
                'verbose_name_plural': 'Ventas Cajero',
            },
        ),
        migrations.AddField(
            model_name='cajero',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajeros', to='api.sucursal'),
        ),
        migrations.AlterUniqueTogether(
            name='cajero',
            unique_together={('nombre', 'sucursal')},
        ),
    ]
