# Generated by Django 4.2.2 on 2025-10-08 01:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_cajero_sucursal_turno_ventacajero_cajero_sucursal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cajero', models.CharField(max_length=100)),
                ('banco', models.CharField(default='Caja General', max_length=100)),
                ('valores_sistema', models.JSONField(default=dict)),
                ('total_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valores_caja', models.JSONField(default=dict)),
                ('total_caja', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diferencias', models.JSONField(default=dict)),
                ('total_diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('REVISADO', 'Revisado')], default='COMPLETADO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cajero_logueado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arqueos', to='api.cajero')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arqueos', to='api.sucursal')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arqueos', to='api.turno')),
            ],
            options={
                'verbose_name': 'Arqueo de Caja',
                'verbose_name_plural': 'Arqueos de Caja',
                'ordering': ['-fecha', '-fecha_creacion'],
                'unique_together': {('fecha', 'cajero', 'banco')},
            },
        ),
    ]
