# Generated by Django 4.2.2 on 2025-10-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_arqueocaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PAGADO', 'Pagado'), ('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado'), ('ANULADA', 'Anulada')], default='PAGADO', max_length=20),
        ),
    ]
