# Generated by Django 4.2.2 on 2025-10-08 17:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_anulada_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_remision', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendedor', models.CharField(max_length=100)),
                ('destinatario', models.CharField(max_length=255)),
                ('direccion_entrega', models.TextField()),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('tipo_remision', models.CharField(choices=[('ENTREGA', 'Entrega'), ('TRASLADO', 'Traslado'), ('DEVOLUCION', 'Devolución'), ('MUESTRA', 'Muestra')], default='ENTREGA', max_length=20)),
                ('transportadora', models.CharField(default='Propia', max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_TRANSITO', 'En Tránsito'), ('ENTREGADA', 'Entregada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20)),
                ('nota', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.remision')),
            ],
        ),
    ]
