# Generated by Django 4.2.2 on 2025-10-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_ruta_to_cargue'),
        ('api', '0025_remision_detalleremision'),
    ]

    operations = [
    ]
