# Generated by Django 4.2.2 on 2025-10-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_merge_20251009_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargueid3',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='cargueid4',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='cargueid5',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='cargueid6',
            name='ruta',
        ),
    ]
