# Generated by Django 4.2.2 on 2025-10-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_cargueid3_ruta_remove_cargueid4_ruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='centro_costo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_predeterminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dia_entrega',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notificar_cartera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notificar_rotacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_lista_precio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vendedor_asignado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
