# Generated by Django 4.2.2 on 2025-10-11 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_cliente_centro_costo_cliente_cliente_predeterminado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planeacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('producto_nombre', models.CharField(max_length=255)),
                ('existencias', models.IntegerField(default=0)),
                ('solicitadas', models.IntegerField(default=0)),
                ('pedidos', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('orden', models.IntegerField(default=0)),
                ('ia', models.IntegerField(default=0)),
                ('usuario', models.CharField(default='Sistema', max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fecha', 'producto_nombre'],
                'unique_together': {('fecha', 'producto_nombre')},
            },
        ),
    ]
