# Generated by Django 4.2.2 on 2025-10-12 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_planeacion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='remision',
            table='api_pedido',
        ),
        migrations.AlterModelTable(
            name='detalleremision',
            table='api_detallepedido',
        ),
    ]
