# Generated by Django 4.2.2 on 2025-10-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_detallepedido_pedido_vendedor_delete_detalleremision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargueid1',
            name='lotes_produccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cargueid2',
            name='lotes_produccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cargueid3',
            name='lotes_produccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cargueid4',
            name='lotes_produccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cargueid5',
            name='lotes_produccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cargueid6',
            name='lotes_produccion',
            field=models.TextField(blank=True),
        ),
    ]
