# Generated by Django 4.2.2 on 2025-10-26 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_agregar_lotes_produccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=10)),
                ('cajero', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
