# Generated by Django 4.2.2 on 2025-11-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_movimientocaja'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arqueocaja',
            unique_together=set(),
        ),
    ]
