# Generated by Django 4.2.2 on 2025-11-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_arqueocaja_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AddField(
            model_name='producto',
            name='orden',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
