# Generated by Django 4.2.2 on 2025-11-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_add_orden_to_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ubicacion_inventario',
            field=models.CharField(choices=[('PRODUCCION', 'Producción'), ('MAQUILA', 'Maquila')], db_index=True, default='PRODUCCION', max_length=20),
        ),
    ]
