# Generated by Django 4.2.2 on 2025-11-10 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_producto_ubicacion_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(default='MI NEGOCIO', max_length=255)),
                ('nit_negocio', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_negocio', models.TextField(blank=True, null=True)),
                ('telefono_negocio', models.CharField(blank=True, max_length=100, null=True)),
                ('email_negocio', models.EmailField(blank=True, max_length=254, null=True)),
                ('encabezado_ticket', models.TextField(blank=True, help_text='Texto que aparece al inicio del ticket', null=True)),
                ('pie_pagina_ticket', models.TextField(blank=True, help_text='Texto que aparece al final del ticket', null=True)),
                ('mensaje_agradecimiento', models.CharField(default='¡Gracias por su compra!', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracion/')),
                ('ancho_papel', models.CharField(choices=[('58mm', '58mm'), ('80mm', '80mm')], default='80mm', max_length=10)),
                ('mostrar_logo', models.BooleanField(default=True)),
                ('mostrar_codigo_barras', models.BooleanField(default=False)),
                ('impresora_predeterminada', models.CharField(blank=True, max_length=255, null=True)),
                ('resolucion_facturacion', models.CharField(blank=True, max_length=255, null=True)),
                ('regimen_tributario', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Impresión',
                'verbose_name_plural': 'Configuraciones de Impresión',
            },
        ),
    ]
