# Generated by Django 4.2.2 on 2025-11-18 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_configuracionimpresion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock', serialize=False, to='api.producto')),
                ('cantidad_actual', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'api_stock',
            },
        ),
    ]
