# Generated by Django 4.2.2 on 2025-11-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='producto_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='producto_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
