# Generated by Django 4.2.2 on 2025-11-20 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_stock_producto_descripcion_stock_producto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domiciliario',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('vehiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('zona_asignada', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Domiciliario',
                'verbose_name_plural': 'Domiciliarios',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='afectar_inventario_inmediato',
            field=models.BooleanField(default=False, verbose_name='Afectar inventario inmediatamente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='asignado_a_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID del vendedor o domiciliario'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='asignado_a_tipo',
            field=models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('DOMICILIARIO', 'Domiciliario'), ('NINGUNO', 'Ninguno')], default='NINGUNO', max_length=20, verbose_name='Tipo de asignación'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='inventario_afectado',
            field=models.BooleanField(default=False, verbose_name='Inventario ya afectado'),
        ),
    ]
