# Generated by Django 4.2.2 on 2025-11-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_domiciliario_zona_asignada'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponible_cargue',
            field=models.BooleanField(default=True, verbose_name='Disponible en Cargue'),
        ),
        migrations.AddField(
            model_name='producto',
            name='disponible_inventario',
            field=models.BooleanField(default=True, verbose_name='Disponible en Inventario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='disponible_pedidos',
            field=models.BooleanField(default=True, verbose_name='Disponible en Pedidos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='disponible_pos',
            field=models.BooleanField(default=True, verbose_name='Disponible en POS'),
        ),
    ]
