# Generated by Django 4.2.2 on 2025-11-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_clienteruta_ruta_ventaruta_clienteruta_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteruta',
            name='tipo_negocio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
