# Generated by Django 4.2.2 on 2025-11-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_clienteruta_tipo_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaruta',
            name='foto_vencidos',
            field=models.ImageField(blank=True, null=True, upload_to='vencidos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='ventaruta',
            name='productos_vencidos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
