# Generated by Django 4.2.2 on 2025-11-28 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_ventaruta_foto_vencidos_ventaruta_productos_vencidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField(blank=True, help_text='ID del producto al que corresponde la foto', null=True)),
                ('imagen', models.ImageField(upload_to='vencidos/%Y/%m/%d/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='api.ventaruta')),
            ],
        ),
    ]
