# Generated by Django 4.2.2 on 2025-11-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_evidenciaventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaruta',
            name='nombre_negocio',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
