# Generated by Django 4.2.2 on 2025-11-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_add_nombre_negocio_to_ventaruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_cargue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Cargue/App'),
        ),
    ]
