# Generated by Django 4.2.2 on 2025-11-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_add_precio_cargue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteruta',
            name='dia_visita',
            field=models.CharField(max_length=100),
        ),
    ]
