# Generated by Django 4.2.2 on 2025-11-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_aumentar_dia_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='password',
            field=models.CharField(default='1234', max_length=50),
        ),
    ]
