# Generated by Django 4.2.2 on 2025-12-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_vendedor_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrosPlaneacionDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('producto_nombre', models.CharField(max_length=200)),
                ('existencias', models.IntegerField(default=0)),
                ('solicitadas', models.IntegerField(default=0)),
                ('pedidos', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('orden', models.IntegerField(default=0)),
                ('ia', models.IntegerField(default=0)),
                ('fecha_congelado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(default='Sistema', max_length=100)),
            ],
            options={
                'verbose_name': 'Registro Planeación Día',
                'verbose_name_plural': 'Registros Planeación Día',
                'db_table': 'api_registros_planeacion_dia',
                'ordering': ['fecha', 'orden'],
                'unique_together': {('fecha', 'producto_nombre')},
            },
        ),
    ]
