# Generated by Django 4.2.2 on 2025-12-03 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_registros_planeacion_dia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargueid1',
            options={'verbose_name': 'Cargue ID1', 'verbose_name_plural': 'Cargues ID1'},
        ),
        migrations.AlterModelOptions(
            name='cargueid2',
            options={'verbose_name': 'Cargue ID2', 'verbose_name_plural': 'Cargues ID2'},
        ),
        migrations.AlterModelOptions(
            name='cargueid3',
            options={'verbose_name': 'Cargue ID3', 'verbose_name_plural': 'Cargues ID3'},
        ),
        migrations.AlterModelOptions(
            name='cargueid4',
            options={'verbose_name': 'Cargue ID4', 'verbose_name_plural': 'Cargues ID4'},
        ),
        migrations.AlterModelOptions(
            name='cargueid5',
            options={'verbose_name': 'Cargue ID5', 'verbose_name_plural': 'Cargues ID5'},
        ),
        migrations.AlterModelOptions(
            name='cargueid6',
            options={'verbose_name': 'Cargue ID6', 'verbose_name_plural': 'Cargues ID6'},
        ),
        migrations.AlterUniqueTogether(
            name='cargueid1',
            unique_together={('dia', 'fecha', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='cargueid2',
            unique_together={('dia', 'fecha', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='cargueid3',
            unique_together={('dia', 'fecha', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='cargueid4',
            unique_together={('dia', 'fecha', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='cargueid5',
            unique_together={('dia', 'fecha', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='cargueid6',
            unique_together={('dia', 'fecha', 'producto')},
        ),
    ]
