# Generated by Django 4.2.2 on 2025-12-03 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_add_unique_constraint_cargue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargueResumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor_id', models.CharField(max_length=3)),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=10)),
                ('fecha', models.DateField()),
                ('base_caja', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_despacho', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pedidos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_dctos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usuario', models.CharField(default='Sistema', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resumen de Cargue',
                'verbose_name_plural': 'Resúmenes de Cargue',
                'db_table': 'api_cargue_resumen',
                'indexes': [models.Index(fields=['vendedor_id', 'fecha'], name='api_cargue__vendedo_be9e37_idx'), models.Index(fields=['fecha'], name='api_cargue__fecha_62f4e1_idx')],
                'unique_together': {('vendedor_id', 'dia', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='CargueProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor_id', models.CharField(max_length=3)),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=10)),
                ('fecha', models.DateField()),
                ('producto', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField(default=0)),
                ('dctos', models.IntegerField(default=0)),
                ('adicional', models.IntegerField(default=0)),
                ('devoluciones', models.IntegerField(default=0)),
                ('vencidas', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('v', models.BooleanField(default=False)),
                ('d', models.BooleanField(default=False)),
                ('lotes_vencidos', models.TextField(blank=True)),
                ('lotes_produccion', models.TextField(blank=True)),
                ('responsable', models.CharField(default='Sistema', max_length=100)),
                ('usuario', models.CharField(default='Sistema', max_length=100)),
                ('ruta', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto de Cargue',
                'verbose_name_plural': 'Productos de Cargue',
                'db_table': 'api_cargue_productos',
                'indexes': [models.Index(fields=['vendedor_id', 'fecha', 'dia'], name='api_cargue__vendedo_6a14f2_idx'), models.Index(fields=['fecha'], name='api_cargue__fecha_d2a36d_idx')],
                'unique_together': {('vendedor_id', 'dia', 'fecha', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='CarguePagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor_id', models.CharField(max_length=3)),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=10)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(blank=True, max_length=255)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nequi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daviplata', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario', models.CharField(default='Sistema', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pago de Cargue',
                'verbose_name_plural': 'Pagos de Cargue',
                'db_table': 'api_cargue_pagos',
                'indexes': [models.Index(fields=['vendedor_id', 'fecha', 'dia'], name='api_cargue__vendedo_540443_idx'), models.Index(fields=['fecha'], name='api_cargue__fecha_39e5c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='CargueCumplimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor_id', models.CharField(max_length=3)),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=10)),
                ('fecha', models.DateField()),
                ('licencia_transporte', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('soat', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('uniforme', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('no_locion', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('no_accesorios', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('capacitacion_carnet', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('higiene', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('estibas', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('desinfeccion', models.CharField(blank=True, choices=[('C', 'Cumple'), ('NC', 'No Cumple')], max_length=2, null=True)),
                ('usuario', models.CharField(default='Sistema', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cumplimiento de Cargue',
                'verbose_name_plural': 'Cumplimientos de Cargue',
                'db_table': 'api_cargue_cumplimiento',
                'indexes': [models.Index(fields=['vendedor_id', 'fecha'], name='api_cargue__vendedo_459f37_idx'), models.Index(fields=['fecha'], name='api_cargue__fecha_3a32a0_idx')],
                'unique_together': {('vendedor_id', 'dia', 'fecha')},
            },
        ),
    ]
