# Generated by Django 4.2.2 on 2025-12-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_crear_tablas_normalizadas_cargue'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponible_app_cargue',
            field=models.BooleanField(default=True, verbose_name='App: Cargue'),
        ),
        migrations.AddField(
            model_name='producto',
            name='disponible_app_rendimiento',
            field=models.BooleanField(default=True, verbose_name='App: Rendimiento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='disponible_app_sugeridos',
            field=models.BooleanField(default=True, verbose_name='App: Sugeridos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='disponible_app_ventas',
            field=models.BooleanField(default=True, verbose_name='App: Ventas'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponible_cargue',
            field=models.BooleanField(default=True, verbose_name='Disponible en Cargue (CRM)'),
        ),
    ]
