# Generated by Django 4.2.2 on 2025-12-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_add_app_disponibilidad_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargueid1',
            name='vendidas',
            field=models.IntegerField(default=0),
        ),
    ]
