# Generated by Django 4.2.2 on 2025-12-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_cargueid1_vendidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargueid2',
            name='vendidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cargueid3',
            name='vendidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cargueid4',
            name='vendidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cargueid5',
            name='vendidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cargueid6',
            name='vendidas',
            field=models.IntegerField(default=0),
        ),
    ]
