# Generated by Django 4.2.2 on 2025-12-19 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_cargueid2_vendidas_cargueid3_vendidas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor_id', models.IntegerField(db_index=True)),
                ('vendedor_nombre', models.CharField(blank=True, max_length=100)),
                ('dia', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('hora_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('total_ventas', models.IntegerField(default=0)),
                ('total_dinero', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dispositivo', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Turno Vendedor',
                'verbose_name_plural': 'Turnos Vendedores',
                'db_table': 'api_turno_vendedor',
                'ordering': ['-fecha', 'vendedor_id'],
                'unique_together': {('vendedor_id', 'fecha')},
            },
        ),
    ]
