# Generated by Django 4.2.2 on 2025-12-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_turno_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionimpresion',
            name='fuente_ticket',
            field=models.CharField(choices=[('Courier New', 'Courier New (Clásico)'), ('Consolas', 'Consolas (Moderno)'), ('Monaco', 'Monaco'), ('Lucida Console', 'Lucida Console'), ('Arial', 'Arial'), ('Verdana', 'Verdana'), ('Tahoma', 'Tahoma')], default='Courier New', max_length=50, verbose_name='Fuente del Ticket'),
        ),
    ]
