# Generated by Django 4.2.2 on 2025-12-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_add_fuente_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargueresumen',
            name='estado_cargue',
            field=models.CharField(choices=[('ALISTAMIENTO', 'Alistamiento'), ('SUGERIDO', 'Sugerido'), ('DESPACHO', 'Despacho'), ('COMPLETADO', 'Completado')], default='ALISTAMIENTO', max_length=20),
        ),
    ]
