# Generated by Django 4.2.2 on 2025-12-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_add_estado_cargue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionProduccion',
            fields=[
                ('clave', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('valor', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Producción',
                'verbose_name_plural': 'Configuraciones de Producción',
                'db_table': 'api_configuracion_produccion',
            },
        ),
    ]
