# Generated by Django 4.2.2 on 2025-12-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_configuracionproduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata')], default='EFECTIVO', max_length=20),
        ),
    ]
