# Generated by Django 4.2.2 on 2025-12-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_add_metodo_pago_to_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20, unique=True)),
                ('clientes_ids', models.JSONField(default=list)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden de Ruta',
                'verbose_name_plural': 'Ordenes de Rutas',
            },
        ),
    ]
