# Generated by Django 4.2.2 on 2026-01-05 16:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_rutaorden'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('collected_params', models.JSONField(default=dict)),
                ('required_params', models.JSONField(default=list)),
                ('current_param_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='api_agentse_created_116938_idx')],
            },
        ),
    ]
