# Generated by Django 4.2.2 on 2026-01-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_agentsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dia_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
