# Generated by Django 4.2.2 on 2026-01-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_cliente_dia_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaruta',
            name='id_local',
            field=models.CharField(blank=True, help_text='ID único de la venta generado en el dispositivo', max_length=50, null=True, unique=True),
        ),
    ]
