# Generated by Django 4.2.2 on 2026-01-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_ventaruta_id_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='novedades',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
