# Generated by Django 4.2.2 on 2026-01-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_pedido_novedades'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionimpresion',
            name='letter_spacing',
            field=models.DecimalField(decimal_places=1, default=-0.2, help_text='Espaciado entre letras (px, negativo para compactar)', max_digits=3),
        ),
        migrations.AddField(
            model_name='configuracionimpresion',
            name='letter_spacing_divider',
            field=models.DecimalField(decimal_places=1, default=-0.8, help_text='Espaciado de divisores (px)', max_digits=3),
        ),
        migrations.AddField(
            model_name='configuracionimpresion',
            name='tamanio_fuente_general',
            field=models.IntegerField(default=14, help_text='Tamaño de fuente general del ticket (px)'),
        ),
        migrations.AddField(
            model_name='configuracionimpresion',
            name='tamanio_fuente_info',
            field=models.IntegerField(default=13, help_text='Tamaño de la información de venta (px)'),
        ),
        migrations.AddField(
            model_name='configuracionimpresion',
            name='tamanio_fuente_nombre_negocio',
            field=models.IntegerField(default=16, help_text='Tamaño del nombre del negocio (px)'),
        ),
        migrations.AddField(
            model_name='configuracionimpresion',
            name='tamanio_fuente_tabla',
            field=models.IntegerField(default=13, help_text='Tamaño de la tabla de productos (px)'),
        ),
        migrations.AddField(
            model_name='configuracionimpresion',
            name='tamanio_fuente_totales',
            field=models.IntegerField(default=13, help_text='Tamaño de los totales (px)'),
        ),
    ]
