# Generated by Django 4.2.2 on 2026-01-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_agregar_estilos_visuales_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionimpresion',
            name='font_weight_tabla',
            field=models.CharField(choices=[('normal', 'Normal'), ('bold', 'Negrita')], default='normal', help_text='Peso de fuente de la tabla de productos', max_length=10),
        ),
    ]
