# Generated by Django 4.2.2 on 2026-01-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_agregar_font_weight_tabla'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionimpresion',
            name='ciudad_negocio',
            field=models.CharField(blank=True, help_text='Ciudad del negocio (ej: BOGOTA)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracionimpresion',
            name='pais_negocio',
            field=models.CharField(blank=True, default='Colombia', help_text='País del negocio', max_length=100, null=True),
        ),
    ]
