# Generated by Django 4.2.2 on 2026-01-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_agregar_ciudad_pais_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='zona_barrio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zona/Barrio'),
        ),
    ]
