# Generated by Django 4.2.2 on 2026-01-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_pedido_zona_barrio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportePlaneacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, default='Sistema', max_length=100, null=True)),
                ('datos_json', models.JSONField()),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
