# Generated by Django 4.2.2 on 2026-01-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_reporteplaneacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteruta',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
