# Generated by Django 4.2.2 on 2026-01-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_clienteruta_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaruta',
            name='dispositivo_id',
            field=models.CharField(blank=True, default='', help_text='Identificador del dispositivo (ej: ANDROID-SAMSUNG-K3J9X2)', max_length=100),
        ),
        migrations.AddField(
            model_name='ventaruta',
            name='ip_origen',
            field=models.GenericIPAddressField(blank=True, help_text='IP desde donde se registró la venta', null=True),
        ),
        migrations.AlterField(
            model_name='ventaruta',
            name='id_local',
            field=models.CharField(blank=True, help_text='ID único: vendedor-dispositivo-timestamp-random', max_length=150, null=True, unique=True),
        ),
    ]
