# Generated by Django 4.2.2 on 2026-01-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_add_multi_device_tracking_ventaruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE_VENTA', 'Crear Venta'), ('CREATE_DUPLICADO', 'Intento Duplicado'), ('UPDATE_CARGUE', 'Actualizar Cargue'), ('CLOSE_TURNO', 'Cerrar Turno'), ('CONFLICT', 'Conflicto Detectado')], max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('registro_id', models.IntegerField(default=0)),
                ('id_local', models.CharField(blank=True, default='', max_length=150)),
                ('vendedor_id', models.CharField(blank=True, default='', max_length=10)),
                ('dispositivo_id', models.CharField(blank=True, default='', max_length=100)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('exito', models.BooleanField(default=True)),
                ('error_mensaje', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Log de Sincronización',
                'verbose_name_plural': 'Logs de Sincronización',
                'db_table': 'api_sync_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['accion', 'timestamp'], name='api_sync_lo_accion_a6020a_idx'), models.Index(fields=['dispositivo_id', 'timestamp'], name='api_sync_lo_disposi_5f2014_idx'), models.Index(fields=['id_local'], name='api_sync_lo_id_loca_08b386_idx')],
            },
        ),
    ]
