# Generated by Django 4.2.2 on 2026-01-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_add_synclog_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(blank=True, help_text='Nombre del producto', max_length=200)),
                ('imagen', models.ImageField(upload_to='evidencias_pedidos/%Y/%m/%d/')),
                ('motivo', models.CharField(blank=True, default='Devolución en entrega', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='api.pedido')),
            ],
            options={
                'verbose_name': 'Evidencia de Pedido',
                'verbose_name_plural': 'Evidencias de Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
