# Generated by Django 4.2.2 on 2026-01-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_add_evidencia_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajero',
            options={'ordering': ['rol', 'nombre'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterUniqueTogether(
            name='cajero',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cajero',
            name='acceso_app_movil',
            field=models.BooleanField(default=False, verbose_name='App Móvil (Ventas Ruta)'),
        ),
        migrations.AddField(
            model_name='cajero',
            name='acceso_cargue',
            field=models.BooleanField(default=False, verbose_name='Cargue Vendedores'),
        ),
        migrations.AddField(
            model_name='cajero',
            name='acceso_configuracion',
            field=models.BooleanField(default=False, verbose_name='Configuración/Admin'),
        ),
        migrations.AddField(
            model_name='cajero',
            name='acceso_inventario',
            field=models.BooleanField(default=False, verbose_name='Inventario'),
        ),
        migrations.AddField(
            model_name='cajero',
            name='acceso_pedidos',
            field=models.BooleanField(default=False, verbose_name='Pedidos/Remisiones'),
        ),
        migrations.AddField(
            model_name='cajero',
            name='acceso_pos',
            field=models.BooleanField(default=False, verbose_name='POS (Punto de Venta)'),
        ),
        migrations.AddField(
            model_name='cajero',
            name='acceso_produccion',
            field=models.BooleanField(default=False, verbose_name='Producción/Planeación'),
        ),
        migrations.AddField(
            model_name='cajero',
            name='acceso_reportes',
            field=models.BooleanField(default=False, verbose_name='Reportes'),
        ),
        migrations.AddField(
            model_name='cajero',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código interno: ID1, ID101, etc.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='rol',
            field=models.CharField(choices=[('CAJERO', 'Cajero POS'), ('VENDEDOR', 'Vendedor App Móvil'), ('REMISIONES', 'Remisiones/Pedidos'), ('SUPERVISOR', 'Supervisor'), ('ADMINISTRADOR', 'Administrador')], default='CAJERO', max_length=20),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajeros', to='api.sucursal'),
        ),
    ]
