# Generated by Django 4.2.2 on 2026-01-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_unificar_usuarios_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajero',
            name='password_plano',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
