# Generated by Django 4.2.2 on 2026-01-20 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_agregar_password_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutaorden',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_dia', to='api.ruta'),
        ),
        migrations.AlterField(
            model_name='rutaorden',
            name='dia',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='rutaorden',
            unique_together={('ruta', 'dia')},
        ),
    ]
