# Generated by Django 4.2.2 on 2026-01-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_add_ruta_to_rutaorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnovendedor',
            name='cerrado_manual',
            field=models.BooleanField(default=False),
        ),
    ]
