# Generated by Django 4.2.2 on 2026-01-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_add_cerrado_manual_to_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='movil',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
