# Generated by Django 4.2.2 on 2026-01-31 21:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_alter_cliente_movil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosFrecuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('productos', models.JSONField(default=list)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_frecuentes', to='api.cliente')),
            ],
            options={
                'verbose_name': 'Productos Frecuentes',
                'verbose_name_plural': 'Productos Frecuentes',
                'unique_together': {('cliente', 'dia')},
            },
        ),
    ]
