# Generated by Django 4.2.2 on 2026-01-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_productosfrecuentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosfrecuentes',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
