# Generated by Django 4.2.2 on 2026-02-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_productosfrecuentes_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaprecio',
            name='visible_pos',
            field=models.BooleanField(default=False),
        ),
    ]
