# Generated by Django 4.2.2 on 2026-02-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_listaprecio_visible_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='creado_por',
            field=models.CharField(default='Sistema', max_length=100),
        ),
    ]
