# Generated by Django 4.2.2 on 2026-02-02 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_venta_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='api.turno'),
        ),
    ]
