# Generated by Django 4.2.2 on 2026-02-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_add_turno_to_movimientocaja'),
    ]

    operations = [
        # Índices para VentaRuta (acelerar consultas de ventas)
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_ventaruta_vendedor ON api_ventaruta(vendedor_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_ventaruta_vendedor;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_ventaruta_fecha ON api_ventaruta(fecha);",
            reverse_sql="DROP INDEX IF EXISTS idx_ventaruta_fecha;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_ventaruta_id_local ON api_ventaruta(id_local);",
            reverse_sql="DROP INDEX IF EXISTS idx_ventaruta_id_local;"
        ),
        
        # Índices para ClienteRuta (acelerar carga de clientes)
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_clienteruta_ruta ON api_clienteruta(ruta_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_clienteruta_ruta;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_clienteruta_dia_visita ON api_clienteruta(dia_visita);",
            reverse_sql="DROP INDEX IF EXISTS idx_clienteruta_dia_visita;"
        ),
        
        # Índices para RutaOrden (acelerar ordenamiento)
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_rutaorden_ruta_dia ON api_rutaorden(ruta_id, dia);",
            reverse_sql="DROP INDEX IF EXISTS idx_rutaorden_ruta_dia;"
        ),
        
        # Índices para Pedido (acelerar consultas de pedidos)
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_pedido_asignado ON api_pedido(asignado_a_id, fecha_entrega);",
            reverse_sql="DROP INDEX IF EXISTS idx_pedido_asignado;"
        ),
    ]
