# Generated by Django 4.2.2 on 2026-02-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_add_indexes_for_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_negocio',
            field=models.CharField(blank=True, help_text='Tipo de negocio: Tienda, Supermercado, Carnicería, etc.', max_length=100, null=True),
        ),
    ]
