# Generated by Django 4.2.2 on 2026-02-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_add_tipo_negocio_to_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Negocio',
                'verbose_name_plural': 'Tipos de Negocio',
                'ordering': ['nombre'],
            },
        ),
    ]
