# Generated by Django 4.2.2 on 2026-02-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_add_tipo_negocio_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargueresumen',
            name='nota',
            field=models.TextField(blank=True, default=''),
        ),
    ]
