# Generated by Django 4.2.2 on 2026-02-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_add_nota_to_cargueresumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaruta',
            name='editada',
            field=models.BooleanField(default=False),
        ),
    ]
