# Generated by Django 4.2.2 on 2026-02-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_add_editada_to_venta_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaruta',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], default='ACTIVA', help_text='Estado de la venta: ACTIVA o ANULADA', max_length=20),
        ),
    ]
