# Generated by Django 4.2.2 on 2026-02-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_add_estado_to_ventaruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='productos_vencidos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
