# Generated by ChatGPT on 2026-02-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_pedido_productos_vencidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedorSesionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=96, unique=True)),
                ('dispositivo_id', models.CharField(blank=True, default='', max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(db_index=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_movil', to='api.vendedor')),
            ],
            options={
                'verbose_name': 'Sesion movil vendedor',
                'verbose_name_plural': 'Sesiones moviles vendedores',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['vendedor', 'activo'], name='api_vendedo_vendedo_ac0ba2_idx'), models.Index(fields=['token', 'activo'], name='api_vendedo_token_99f8f0_idx')],
            },
        ),
    ]
