# Generated by ChatGPT on 2026-02-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_vendedorsesiontoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaOrdenVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('clientes_ids', models.JSONField(default=list)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_clientes_dia', to='api.vendedor')),
            ],
            options={
                'verbose_name': 'Orden de Vendedor por Día',
                'verbose_name_plural': 'Ordenes de Vendedores por Día',
                'unique_together': {('vendedor', 'dia')},
                'indexes': [models.Index(fields=['vendedor', 'dia'], name='api_rutaord_vendedo_50c290_idx')],
            },
        ),
    ]

