# Generated by Django 4.2.2 on 2026-02-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_rutaordenvendedor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rutaordenvendedor',
            new_name='api_rutaord_vendedo_6f00b4_idx',
            old_name='api_rutaord_vendedo_50c290_idx',
        ),
        migrations.RenameIndex(
            model_name='vendedorsesiontoken',
            new_name='api_vendedo_vendedo_7ae7d5_idx',
            old_name='api_vendedo_vendedo_ac0ba2_idx',
        ),
        migrations.RenameIndex(
            model_name='vendedorsesiontoken',
            new_name='api_vendedo_token_4f0d56_idx',
            old_name='api_vendedo_token_99f8f0_idx',
        ),
    ]
