# Generated by Django 4.2.2 on 2026-03-06 00:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_rename_api_rutaord_vendedo_50c290_idx_api_rutaord_vendedo_6f00b4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='permitir_crear_cliente',
            field=models.BooleanField(default=True, help_text='Habilitar/deshabilitar crear cliente desde la app móvil'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tope_cliente_ocasional',
            field=models.DecimalField(decimal_places=2, default=60000, help_text='Tope máximo de venta para clientes ocasionales', max_digits=12),
        ),
        migrations.CreateModel(
            name='ClienteOcasional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('tope_venta', models.DecimalField(decimal_places=2, default=60000, help_text='Tope máximo de venta para este cliente', max_digits=12)),
                ('convertido', models.BooleanField(default=False, help_text='True si fue convertido a cliente de ruta')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente_ruta', models.ForeignKey(blank=True, help_text='Referencia al ClienteRuta si fue convertido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origen_ocasional', to='api.clienteruta')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_ocasionales', to='api.vendedor')),
            ],
            options={
                'verbose_name': 'Cliente Ocasional',
                'verbose_name_plural': 'Clientes Ocasionales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='ventaruta',
            name='cliente_ocasional',
            field=models.ForeignKey(blank=True, help_text='Si la venta fue a un cliente ocasional', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='api.clienteocasional'),
        ),
    ]
