# Generated by Django 4.2.2 on 2026-03-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_add_cliente_ocasional_y_permisos_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='permitir_venta_rapida',
            field=models.BooleanField(default=True, help_text='Habilitar/deshabilitar venta rápida (cliente ocasional) desde la app'),
        ),
    ]
