# Generated by Django 4.2.2 on 2026-03-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_add_permitir_venta_rapida'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='editada',
            field=models.BooleanField(default=False, verbose_name='Editado desde App'),
        ),
    ]
