# Generated by Django 4.2.2 on 2026-03-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_pedido_editada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaruta',
            name='intentos_anulacion',
            field=models.IntegerField(default=0, help_text='Contador de veces que se ha anulado esta venta (máximo 1 permitido)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('RUT', 'RUT'), ('CE', 'Cédula de extranjería'), ('PASAPORTE', 'Pasaporte')], default='CC', max_length=20),
        ),
    ]
