# Generated by Django 4.2.2 on 2026-03-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_ventaruta_intentos_anulacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaruta',
            name='metodo_pago_cambiado',
            field=models.BooleanField(default=False),
        ),
    ]
