# Generated by Django 4.2.2 on 2026-04-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_add_metodo_pago_cambiado_ventaruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='verificado_despachador',
            field=models.BooleanField(default=False, verbose_name='Verificado por despachador'),
        ),
    ]
