# Generated by Django 4.2.2 on 2026-04-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_add_verificado_despachador_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaruta',
            name='fecha_ultima_edicion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última edición de productos/vencidas', null=True),
        ),
    ]
