# Generated by Django 4.2.2 on 2026-04-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_add_fecha_ultima_edicion_venta_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='tipo_origen',
            field=models.CharField(choices=[('PRODUCCION', 'Producción'), ('MAQUILA', 'Maquila')], default='PRODUCCION', max_length=20),
        ),
    ]
