"""
Django settings for backend_crm project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^zvl@rxk@+w1^4-s!ncx9dhopbzmvry0a1ybp0k#h8vha^&px3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# ...

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React en desarrollo
    "http://localhost:19006", # React Native con Expo, por ejemplo
    "http://192.168.1.19:8081", # Expo Go
    "https://casteless-floodless-clement.ngrok-free.dev",  # ngrok
    # ...
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
      # Apps de terceros
    'rest_framework',
    'corsheaders',

    # Tu aplicación
    'api',
]

# Configuración para almacenamiento de archivos
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Middleware de CORS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'backend_crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_crm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import os

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DATABASE_NAME', 'fabrica'),
        'USER': os.environ.get('DATABASE_USER', 'postgres'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', '12345'),
        'HOST': os.environ.get('DATABASE_HOST', 'localhost'),
        'PORT': os.environ.get('DATABASE_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React en desarrollo
    "http://localhost:19006", # React Native con Expo, por ejemplo
    "https://casteless-floodless-clement.ngrok-free.dev",  # ngrok
    "https://crm-frontend.loca.lt",  # localtunnel frontend
    "https://crm-backend.loca.lt",  # localtunnel backend
    "https://08caf7062a800a3b0ef90c12356c97df.serveo.net",  # serveo backend current
    "https://7e2df673004ea9662b956964d08a71ba.serveo.net",  # serveo frontend
    "https://006cf2b77b37b2a1d5e40ee484d0d8ed.serveo.net",  # serveo frontend old
    "https://eab2deebe213b9852ec8afe871145467.serveo.net",  # serveo backend old
    "https://304e7bc66be9f18ca48e31a1d760746c.serveo.net",  # serveo frontend new
    "https://a6b00d01111f194c2178501e3ee82d44.serveo.net",  # serveo backend new
]

# Permitir credenciales en CORS
CORS_ALLOW_CREDENTIALS = True

# Headers adicionales para ngrok, localtunnel y serveo
CSRF_TRUSTED_ORIGINS = [
    "https://casteless-floodless-clement.ngrok-free.dev",
    "https://crm-backend.loca.lt",
    "https://crm-frontend.loca.lt",
    "https://08caf7062a800a3b0ef90c12356c97df.serveo.net",
    "https://7e2df673004ea9662b956964d08a71ba.serveo.net",
    "https://006cf2b77b37b2a1d5e40ee484d0d8ed.serveo.net",
    "https://eab2deebe213b9852ec8afe871145467.serveo.net",
    "https://304e7bc66be9f18ca48e31a1d760746c.serveo.net",
    "https://a6b00d01111f194c2178501e3ee82d44.serveo.net",
]

